### ISSUE TITLE
Some images broken

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/lqcd-tikz-graphics#1]
@chelmes, some of your images depend on styles defined elsewhere. Could you copy the missing styles into the files such that they are self-contained?

**Comment by chelmes** [comment]
@martin-ueding, Sorry, I forgot. I will take care of it immediately, just need to find out where the graphics came from ...

**Comment by chelmes** [comment]
@martin-ueding, Solved. Had to include mathds for a woprking Gamma-identity and forgot to include some tikz styles.
